# Generated by Django 3.2.9 on 2021-12-16 19:22

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total Area')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('discovery_date', models.DateTimeField(blank=True, verbose_name='Discovery Date')),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'ordering': ['id'],
            },
        ),
    ]
