# Generated by Django 3.2.9 on 2022-01-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
