name: telegram message

on:
  pull_request:
    branches: [ "dev", "main" ]
    paths-ignore: [ "docs/**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{ github.actor }}* created commit on *${{ github.repository }}*
            ${{ github.event.commits[0].message }}
            [See changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          format: markdown
          disable_web_page_preview: true
